/* phases.js — As fases do plano. Cada `tasks[]` vira checkbox que conta no progresso.
   `start`/`end` = semanas no cronograma. `color`/`bg` = identidade visual (hex). */
export default [
  { tag:'Setup', name:'Orientação & pré-requisitos', weeks:'Sem 1–4', color:'#64748b', bg:'#f8fafc', start:1, end:4,
    goal:'Entender o terreno, confirmar pré-requisitos e montar a base operacional',
    desc:'A fase mais subestimada. Sem um mapa claro — e sem as credenciais que destravam o exame — você estuda os tópicos certos da forma errada. No CTA isso custa US$ 4.500.',
    tasks:[
      'Mapear as 2 etapas: Evaluation (US$ 1.500) e Review Board Exam (US$ 4.500)',
      'Confirmar pré-requisito: credencial Salesforce Application Architect ativa',
      'Confirmar pré-requisito: credencial Salesforce System Architect ativa',
      'Listar exames de arquiteto ainda faltantes e encaixá-los no cronograma',
      'Setup de ferramentas: Kryterion, Trailhead, Anki, planner semanal',
      'Self-assessment detalhado nos 7 domínios do Exam Guide',
      'Testar a rotina de menos de 1h/dia adaptada à vida com filhos',
      'Entrar nas comunidades: Architect Ohana, CTA Gang of Four, Architect Trailblazers'] },
  { tag:'Crítico', name:'Nivelamento de gaps', weeks:'Sem 5–30', color:'#dc2626', bg:'#fff5f5', start:5, end:30,
    goal:'Elevar áreas fracas ao nível das já fortes',
    desc:'Suas forças cobrem boa parte do que a banca avalia. O risco real está em Security, Heroku e Mobile — domínios que avaliadores exploram ativamente nos cenários.',
    tasks:[
      'Sem 5–12: Security & Identity — OAuth, SAML, Shield, Event Monitoring',
      'Sem 13–20: Heroku & Platform — Connect, Private Spaces, quando usar cada um',
      'Sem 21–24: Mobile Architecture — SDK, SmartStore offline, push',
      'Sem 25–30: Data Architecture — LDV, data skew, Salesforce Connect, archiving',
      'Contínuo: 30 min/semana revisando áreas fortes para não atrofiar',
      'Concluir os 4 domínios da aba Gaps com 80%+ marcado'] },
  { tag:'Etapa 1 · Prep', name:'Preparação — Evaluation', weeks:'Sem 31–43', color:'#d97706', bg:'#fffbeb', start:31, end:43,
    goal:'Dominar o formato: ler, projetar e defender um cenário focado',
    desc:'A Evaluation é uma mini Review Board: você resolve um cenário e justifica cada decisão perante 1 CTA avaliador, em inglês.',
    tasks:[
      'Completar os 3 mocks de Evaluation com cronômetro real',
      'Desenvolver narrativa: "escolhi X porque Y, descartei Z porque W"',
      'Participar de grupos de mock review (Architect Ohana / Gang of Four)',
      'Treinar justificativa oral em inglês — skill separada da solução',
      'Atingir 80%+ consistente nos mocks antes de registrar',
      'Registrar e agendar a Architect Evaluation'] },
  { tag:'Exame', name:'Architect Evaluation', weeks:'Sem ~44', color:'#16a34a', bg:'#f0fdf4', start:44, end:45,
    goal:'Ser aprovado na Etapa 1 do processo CTA',
    desc:'Online via Kryterion. Um CTA sênior avalia sua solução para um cenário simplificado. A aprovação destrava o caminho para o Review Board Exam.',
    tasks:[
      'Revisão final: rever os 3 mocks de Evaluation e flashcards-chave',
      'Fazer a Architect Evaluation (60 min solução + ~45 min Q&A)',
      'Se aprovado: avançar para a Fase 4 com momentum',
      'Se reprovado: retake (US$ 750) após 4–6 semanas de refino focado'] },
  { tag:'Etapa 2 · Prep', name:'Preparação — Review Board', weeks:'Sem 45–80', color:'#2563eb', bg:'#eff6ff', start:45, end:80,
    goal:'Preparar defesa completa perante 3 CTAs sênior',
    desc:'O estágio mais exigente. 180 min para montar solução e artefatos, 45 min de apresentação e 40 min de Q&A — sem anotações, sem materiais externos.',
    tasks:[
      'Completar os 3 mocks de Review Board (180 min cada)',
      'Treinar artefatos à mão / Google Slides em tempo real',
      'CTA Workshop oficial CTA601 (virtual, altamente recomendado)',
      'Mock Reviews completos — mínimo 1 sessão/mês com feedback real',
      'Treinar apresentação de 45 min e Q&A de 40 min em inglês',
      'Atingir aprovação consistente em mocks com banca antes de agendar',
      'Registrar e agendar o Review Board Exam (planejar viagem)'] },
  { tag:'CTA', exam:true, name:'Review Board Exam', weeks:'Sem ~81', color:'#7c3aed', bg:'#f5f3ff', start:81, end:82,
    goal:'Conquistar o CTA',
    desc:'Presencial em escritório Salesforce. Você entra como candidato e sai — se aprovado — como um dos menos de 1.000 Salesforce CTAs ativos no mundo.',
    tasks:[
      '180 min de preparação isolada: cenário + solução completa com artefatos',
      'Apresentação de 45 min perante 3 CTAs sênior, sem material externo',
      'Q&A de 40 min defendendo cada decisão arquitetural',
      'Planejar viagem ao escritório Salesforce com antecedência',
      'Aprovado: você é oficialmente um Salesforce Certified Technical Architect'] },
];
