/* phases.js — As fases do plano. Cada `tasks[]` vira checkbox que conta no progresso.
   `start`/`end` = semanas no cronograma. `color`/`bg` = identidade visual (hex). */
export default [
  { tag:'Setup', name:'Fundamentos Salesforce', weeks:'Sem 1–2', color:'#0ea5e9', bg:'#f0f9ff', start:1, end:2,
    goal:'Entender a plataforma e como ela se organiza antes de construir qualquer coisa',
    desc:'A base de tudo. 23% das questões cobrem fundamentos — quem são os objetos standard, como a segurança funciona (OWD, perfis, papéis) e o que são relatórios e dashboards. Sem essa base sólida, os domínios seguintes ficam confusos.',
    tasks:[
      'Criar conta no Trailhead e ativar Developer Org gratuita em trailhead.salesforce.com',
      'Completar "Salesforce Platform Basics" no Trailhead — navegação, AppExchange, mobile',
      'Completar "User Management" no Trailhead — perfis, permission sets, papéis (Roles)',
      'Completar "Data Security" no Trailhead — OWD, sharing rules, field-level security',
      'Completar "Reports & Dashboards for Lightning Experience" no Trailhead',
      'Iniciar a Trailmix oficial "Prepare for Your Salesforce Platform App Builder Credential"',
      'Baixar e ler o Exam Guide oficial (PDF em developer.salesforce.com): 5 domínios e pesos',
    ]},
  { tag:'Domínio 2', name:'Modelagem de Dados e Gerenciamento', weeks:'Sem 3–4', color:'#8b5cf6', bg:'#f5f3ff', start:3, end:4,
    goal:'Dominar objetos, campos, relacionamentos e ferramentas de dados',
    desc:'22% do exame. É o bloco de construção de qualquer app Salesforce — quem não sabe modelar dados faz escolhas erradas de automação e UI. Pratique na Developer Org; criar objetos e relacionamentos com as mãos consolida muito mais que só ler.',
    tasks:[
      'Completar "Data Modeling" no Trailhead — standard/custom objects, fields, relacionamentos',
      'Praticar na Developer Org: criar 2 objetos customizados com tipos de campos variados',
      'Criar os 3 tipos de relacionamento na org: Lookup, Master-Detail e Many-to-Many (Junction Object)',
      'Completar "Data Management" no Trailhead — Import Wizard, Data Loader, Export',
      'Estudar Record Types: quando criar e como combinam com Page Layouts',
      'Criar 1 Formula Field e 1 Roll-Up Summary Field na Developer Org',
      'Resolver 20 questões de Data Modeling no Salesforce Ben (salesforceben.com) ou ExamTopics',
    ]},
  { tag:'Domínio 1', name:'Lógica de Negócio e Automação', weeks:'Sem 5–6', color:'#dc2626', bg:'#fff5f5', start:5, end:6,
    goal:'Construir automações com Flow, Approval Processes e Validation Rules',
    desc:'O maior domínio: 28% das questões. Foco quase total em Flows — Salesforce substituiu Process Builder e Workflow Rules por Flows. Para iniciantes, é o ponto onde mais questões são perdidas. Reserve tempo extra para praticar na org.',
    tasks:[
      'Completar "Flow Basics" no Trailhead — tipos de Flow e quando usar cada um',
      'Criar na Developer Org: 2 Record-Triggered Flows (ex.: preencher campo ao criar/editar registro)',
      'Criar na Developer Org: 1 Screen Flow para coleta de dados em múltiplas etapas',
      'Completar "Approval Processes" no Trailhead e criar 1 processo de aprovação na org',
      'Completar "Formulas and Validations" no Trailhead — criar 5 Validation Rules na org',
      'Revisar decisão-chave: Flow vs. Apex — regra: declarativo primeiro, código só quando necessário',
      'Resolver 30 questões de Process Automation no Salesforce Ben e ExamTopics',
    ]},
  { tag:'Domínio 4', name:'Interface do Usuário', weeks:'Sem 6–7', color:'#d97706', bg:'#fffbeb', start:6, end:7,
    goal:'Customizar a interface Lightning sem escrever código',
    desc:'17% do exame. Cobre Lightning App Builder, page layouts, componentes, quick actions e a experiência mobile. Mais visual e prático — quem sabe o que é possível "point-and-click" na UI não precisa cogitar código prematuramente.',
    tasks:[
      'Completar "Lightning App Builder" no Trailhead — criação de páginas e componentes',
      'Criar na Developer Org: uma app Lightning customizada com 3 abas e menu de navegação',
      'Customizar Record Pages com componentes dinâmicos (Visibility Rules) no App Builder',
      'Criar Quick Actions: Object-Level e Global Actions com formulários customizados',
      'Estudar Compact Layouts e List Views customizadas na org',
      'Completar "AppExchange Basics" — como instalar pacotes, diferença entre Managed e Unmanaged',
    ]},
  { tag:'Domínio 5', name:'Deploy de Aplicações', weeks:'Sem 7', color:'#16a34a', bg:'#f0fdf4', start:7, end:7,
    goal:'Entender ambientes Salesforce e como mover customizações entre eles',
    desc:'O menor domínio: 10% das questões, mas diretas e objetivas — pontuam bem com pouco estudo. Foco em sandboxes (tipos e usos), Change Sets (o que entra e o que não entra) e conceitos de Managed vs. Unmanaged packages.',
    tasks:[
      'Completar "Change Sets and Deployment" no Trailhead',
      'Mapear os 4 tipos de Sandbox: Developer, Developer Pro, Partial Copy, Full — quando usar cada',
      'Listar o que PODE e o que NÃO PODE ser incluído num Change Set (ponto frequente no exame)',
      'Revisar: Managed vs. Unmanaged Packages — diferença de proteção de código e distribuição',
    ]},
  { tag:'Revisão', name:'Simulados e Revisão Final', weeks:'Sem 8', color:'#7c3aed', bg:'#f5f3ff', start:8, end:8,
    goal:'Atingir ≥ 70% nos simulados e consolidar os pontos fracos antes do exame',
    desc:'A semana mais importante. Simulados identificam lacunas que o estudo teórico não mostra. Meta: acertar ≥ 70% consistentemente (7 pontos acima do mínimo de 63%) antes de sentar no exame real.',
    tasks:[
      'Simulado 1 completo (gratuito): Salesforce Ben — 60 questões, 105 min cronometrado',
      'Revisar respostas erradas do Simulado 1 e anotar os domínios com pior desempenho',
      'Simulado 2 completo (gratuito): ExamTopics ou Practice Test Geeks — banco diferente do 1',
      'Revisitar módulos Trailhead dos domínios com < 60% de acerto',
      'Simulado 3 completo (Udemy em promoção ou Simplilearn): confirmar ≥ 70%',
      'Revisão final: percorrer todos os tópicos da aba Gaps e consolidar o que ficou incerto',
      'Confirmar data, horário e local do exame no Webassessor (trailhead.salesforce.com)',
    ]},
  { tag:'Exame', name:'Exame Platform App Builder', weeks:'Sem 9', color:'#16a34a', bg:'#f0fdf4', start:9, end:9,
    goal:'Ser aprovado com ≥ 63% (38 de 60 questões pontuadas)',
    desc:'Online via Pearson VUE / Webassessor. 65 questões (60 pontuadas + 5 não pontuadas), 105 minutos. Aprovação com 63% de acerto. Retake disponível por US$ 100 caso necessário.',
    tasks:[
      'Revisão express na véspera: flashcards de pontos críticos, máx. 30 min — sem conteúdo novo',
      'Fazer o exame Platform App Builder (65 questões, 105 min, ≥ 63% para aprovação)',
      'Aprovado: você é um Salesforce Certified Platform App Builder!',
    ]},
];
